In [3]:
import numpy as np

lst=[1,2,3]
arr=np.array(lst)
arr

array([1, 2, 3])

In [5]:
arr1=np.array([[1,2,3],[4,5,6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr1.shape

(2, 3)

In [7]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [9]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [10]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [11]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr1.dtype

dtype('int32')

In [14]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [17]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [18]:
np.arange(1,20,2).reshape(2,5)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [20]:
np.arange(1,20,2).reshape(5,2).shape

(5, 2)

In [21]:
range(1,20,2)

range(1, 20, 2)

In [22]:
list(range(1,20,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [23]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [26]:
np.linspace(1,20,40)

array([ 1.        ,  1.48717949,  1.97435897,  2.46153846,  2.94871795,
        3.43589744,  3.92307692,  4.41025641,  4.8974359 ,  5.38461538,
        5.87179487,  6.35897436,  6.84615385,  7.33333333,  7.82051282,
        8.30769231,  8.79487179,  9.28205128,  9.76923077, 10.25641026,
       10.74358974, 11.23076923, 11.71794872, 12.20512821, 12.69230769,
       13.17948718, 13.66666667, 14.15384615, 14.64102564, 15.12820513,
       15.61538462, 16.1025641 , 16.58974359, 17.07692308, 17.56410256,
       18.05128205, 18.53846154, 19.02564103, 19.51282051, 20.        ])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [29]:
np.ones(10).reshape(2,5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [32]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
5+ np.ones((3,4))

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [37]:
np.eye(4).reshape(2,8)

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [38]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [39]:
print("random number generation (uniform distribution)")
np.random.rand(2,3)

random number generation (uniform distribution)


array([[0.74780231, 0.04939008, 0.58827173],
       [0.17252255, 0.18784273, 0.12583932]])

In [41]:
print("Random number following a normal distribution with mean=0 and std=1")

print(np.random.randn(5,3))

Random number following a normal distribution with mean=0 and std=1
[[ 0.04530896 -0.18478029 -0.39824761]
 [ 0.85078466  0.5784209   0.5404782 ]
 [ 0.47338039 -1.92807224  0.53274305]
 [ 0.52232303  2.6739946   1.04170469]
 [-1.80871694 -0.02819984 -1.44910511]]


In [47]:
np.random.randint(1,20,5)

array([ 2, 12,  2, 16,  4])

In [48]:
np.random.randint(1,100,(5,6))

array([[16, 58,  3, 25, 65, 73],
       [27, 28, 65, 84, 65, 11],
       [93, 58, 61, 24, 21, 69],
       [83, 47, 81, 43, 72, 40],
       [18, 50, 78, 11, 94, 80]])

In [49]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [55]:
arr[-1:7:-1]

array([10,  9,  8])

In [57]:
arr[-1:3:-2]

array([10,  8,  6,  4])

In [60]:
arr1=np.arange(1,21).reshape(5,4)

In [61]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [64]:
arr1[0:3]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
arr1[0:3,0:3]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [67]:
arr1[3:,1:]

array([[14, 15, 16],
       [18, 19, 20]])

In [69]:
arr1[2:4,1:3]

array([[10, 11],
       [14, 15]])

In [72]:
arr1[2:4,0:4:3]

array([[ 9, 12],
       [13, 16]])

In [89]:
# #universal functions

arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(5,50,(3,3))

In [90]:
print(arr1)
print(arr2)

[[87 85 84]
 [91 21 90]
 [ 9 48 96]]
[[28 12 33]
 [48 37 22]
 [ 8 10 36]]


In [77]:
arr1 + arr2

array([[ 74,  73,  77],
       [ 63,  80,  35],
       [115,  96,  36]])

In [78]:
arr1 * arr2

array([[ 793, 1260, 1350],
       [ 962, 1564,  216],
       [2964, 2183,  128]])

In [79]:
np.sqrt(arr1)

array([[7.81024968, 6.70820393, 7.07106781],
       [5.09901951, 6.78232998, 5.19615242],
       [8.71779789, 7.68114575, 2.        ]])

In [80]:
np.log10(arr2)

array([[1.11394335, 1.44715803, 1.43136376],
       [1.56820172, 1.53147892, 0.90308999],
       [1.59106461, 1.56820172, 1.50514998]])

In [81]:
arr1=np.arange(1,10)

In [82]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
arr1[2:]=100

In [84]:
arr1

array([  1,   2, 100, 100, 100, 100, 100, 100, 100])

In [91]:
np.dot(arr1,arr2)

array([[7188, 5029, 7765],
       [4276, 2769, 6705],
       [3324, 2844, 4809]])

In [92]:
np.cross(arr1,arr2)

array([[ 1797,  -519, -1336],
       [-2868,  2318,  2359],
       [  768,   444,  -294]])

In [93]:
np.matmul(arr1,arr2)

array([[7188, 5029, 7765],
       [4276, 2769, 6705],
       [3324, 2844, 4809]])